// Generated by gencpp from file huskyterrain/imutrans.msg
// DO NOT EDIT!


#ifndef HUSKYTERRAIN_MESSAGE_IMUTRANS_H
#define HUSKYTERRAIN_MESSAGE_IMUTRANS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Imu.h>
#include <geometry_msgs/Vector3.h>

namespace huskyterrain
{
template <class ContainerAllocator>
struct imutrans_
{
  typedef imutrans_<ContainerAllocator> Type;

  imutrans_()
    : header()
    , pose()
    , angular_acceleration()
    , coorx(0.0)
    , coory(0.0)
    , id(0)
    , sampling_rate(0)  {
    }
  imutrans_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , angular_acceleration(_alloc)
    , coorx(0.0)
    , coory(0.0)
    , id(0)
    , sampling_rate(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_acceleration_type;
  _angular_acceleration_type angular_acceleration;

   typedef float _coorx_type;
  _coorx_type coorx;

   typedef float _coory_type;
  _coory_type coory;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _sampling_rate_type;
  _sampling_rate_type sampling_rate;




  typedef boost::shared_ptr< ::huskyterrain::imutrans_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::huskyterrain::imutrans_<ContainerAllocator> const> ConstPtr;

}; // struct imutrans_

typedef ::huskyterrain::imutrans_<std::allocator<void> > imutrans;

typedef boost::shared_ptr< ::huskyterrain::imutrans > imutransPtr;
typedef boost::shared_ptr< ::huskyterrain::imutrans const> imutransConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::huskyterrain::imutrans_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::huskyterrain::imutrans_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace huskyterrain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'huskyterrain': ['/home/vsung/catkin_ws/src/huskyterrain/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::huskyterrain::imutrans_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::huskyterrain::imutrans_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::huskyterrain::imutrans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::huskyterrain::imutrans_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::huskyterrain::imutrans_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::huskyterrain::imutrans_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::huskyterrain::imutrans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6ceccfc5eff5b49731f1f199301e128";
  }

  static const char* value(const ::huskyterrain::imutrans_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6ceccfc5eff5b49ULL;
  static const uint64_t static_value2 = 0x731f1f199301e128ULL;
};

template<class ContainerAllocator>
struct DataType< ::huskyterrain::imutrans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "huskyterrain/imutrans";
  }

  static const char* value(const ::huskyterrain::imutrans_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::huskyterrain::imutrans_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
sensor_msgs/Imu pose\n\
geometry_msgs/Vector3 angular_acceleration\n\
float32 coorx\n\
float32 coory\n\
int32 id\n\
int32 sampling_rate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Imu\n\
# This is a message to hold data from an IMU (Inertial Measurement Unit)\n\
#\n\
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n\
#\n\
# If the covariance of the measurement is known, it should be filled in (if all you know is the \n\
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n\
# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n\
# data a covariance will have to be assumed or gotten from some other source\n\
#\n\
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n\
# estimate), please set element 0 of the associated covariance matrix to -1\n\
# If you are interpreting this message, please check for a value of -1 in the first element of each \n\
# covariance matrix, and disregard the associated estimate.\n\
\n\
Header header\n\
\n\
geometry_msgs/Quaternion orientation\n\
float64[9] orientation_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 angular_velocity\n\
float64[9] angular_velocity_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 linear_acceleration\n\
float64[9] linear_acceleration_covariance # Row major x, y z \n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::huskyterrain::imutrans_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::huskyterrain::imutrans_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.angular_acceleration);
      stream.next(m.coorx);
      stream.next(m.coory);
      stream.next(m.id);
      stream.next(m.sampling_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imutrans_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::huskyterrain::imutrans_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::huskyterrain::imutrans_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "angular_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_acceleration);
    s << indent << "coorx: ";
    Printer<float>::stream(s, indent + "  ", v.coorx);
    s << indent << "coory: ";
    Printer<float>::stream(s, indent + "  ", v.coory);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "sampling_rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sampling_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKYTERRAIN_MESSAGE_IMUTRANS_H
