// Generated by gencpp from file huskyterrain/view_poly.msg
// DO NOT EDIT!


#ifndef HUSKYTERRAIN_MESSAGE_VIEW_POLY_H
#define HUSKYTERRAIN_MESSAGE_VIEW_POLY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>

namespace huskyterrain
{
template <class ContainerAllocator>
struct view_poly_
{
  typedef view_poly_<ContainerAllocator> Type;

  view_poly_()
    : header()
    , pointcloud()
    , coorx()
    , coory()
    , id()  {
      coorx.assign(0.0);

      coory.assign(0.0);

      id.assign(0);
  }
  view_poly_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pointcloud(_alloc)
    , coorx()
    , coory()
    , id()  {
  (void)_alloc;
      coorx.assign(0.0);

      coory.assign(0.0);

      id.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;

   typedef boost::array<float, 30>  _coorx_type;
  _coorx_type coorx;

   typedef boost::array<float, 30>  _coory_type;
  _coory_type coory;

   typedef boost::array<int32_t, 30>  _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::huskyterrain::view_poly_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::huskyterrain::view_poly_<ContainerAllocator> const> ConstPtr;

}; // struct view_poly_

typedef ::huskyterrain::view_poly_<std::allocator<void> > view_poly;

typedef boost::shared_ptr< ::huskyterrain::view_poly > view_polyPtr;
typedef boost::shared_ptr< ::huskyterrain::view_poly const> view_polyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::huskyterrain::view_poly_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::huskyterrain::view_poly_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace huskyterrain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'huskyterrain': ['/home/vsung/catkin_ws/src/huskyterrain/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::huskyterrain::view_poly_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::huskyterrain::view_poly_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::huskyterrain::view_poly_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::huskyterrain::view_poly_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::huskyterrain::view_poly_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::huskyterrain::view_poly_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::huskyterrain::view_poly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e5e6be4258eabd9727fb48bf28593dc";
  }

  static const char* value(const ::huskyterrain::view_poly_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e5e6be4258eabd9ULL;
  static const uint64_t static_value2 = 0x727fb48bf28593dcULL;
};

template<class ContainerAllocator>
struct DataType< ::huskyterrain::view_poly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "huskyterrain/view_poly";
  }

  static const char* value(const ::huskyterrain::view_poly_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::huskyterrain::view_poly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
sensor_msgs/PointCloud2 pointcloud\n\
float32[30] coorx\n\
float32[30] coory\n\
int32[30] id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
";
  }

  static const char* value(const ::huskyterrain::view_poly_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::huskyterrain::view_poly_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pointcloud);
      stream.next(m.coorx);
      stream.next(m.coory);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct view_poly_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::huskyterrain::view_poly_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::huskyterrain::view_poly_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
    s << indent << "coorx[]" << std::endl;
    for (size_t i = 0; i < v.coorx.size(); ++i)
    {
      s << indent << "  coorx[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coorx[i]);
    }
    s << indent << "coory[]" << std::endl;
    for (size_t i = 0; i < v.coory.size(); ++i)
    {
      s << indent << "  coory[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coory[i]);
    }
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKYTERRAIN_MESSAGE_VIEW_POLY_H
